drop table if exists ChargerStations cascade;
drop table if exists ChargerSessions cascade;

CREATE TABLE IF NOT EXISTS ChargerStations
(
    station_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    address VARCHAR(254) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    is_available BOOLEAN NOT NULL
);

INSERT INTO ChargerStations (name, address, latitude, longitude, is_available)
VALUES ('Station One', '123 Main St', 54.68916, 25.2798, true);

INSERT INTO ChargerStations (name, address, latitude, longitude, is_available)
VALUES ('Station Two', '456 Elm St', 54.68917, 25.2799, false);

INSERT INTO ChargerStations (name, address, latitude, longitude, is_available)
VALUES ('Station Three', '789 Oak St', 54.68918, 25.2800, true);


CREATE TABLE IF NOT EXISTS ChargerSessions
(
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT REFERENCES ChargerStations(station_id),
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    car_id BIGINT NOT NULL
);


