drop table if exists chargerstations cascade;
drop table if exists chargersessions cascade;

CREATE TABLE IF NOT EXISTS chargerstations
(
    station_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    address VARCHAR(254) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    is_available BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS chargersessions
(
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT REFERENCES chargerstations(station_id),
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    car_id BIGINT NOT NULL
);


