drop table if exists chargerstations cascade;

CREATE TABLE IF NOT EXISTS chargerstations
(
    station_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    address VARCHAR(254) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    is_available BOOLEAN NOT NULL
);



