drop table if exists cars cascade;

CREATE TABLE IF NOT EXISTS cars
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model                   VARCHAR(254) NOT NULL,
    manufacturer            VARCHAR(254) NOT NULL,
    battery_capacity_in_kwh DOUBLE PRECISION,
    mileage_in_kilometers   INTEGER,
    range_in_kilometers     INTEGER,
    status                  SMALLINT     NOT NULL,
    cost_per_minute         NUMERIC(10, 2),
    issues                  TEXT
);