drop table if exists notifications cascade;

CREATE TABLE IF NOT EXISTS notifications
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    type VARCHAR(50),
    message VARCHAR(512),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);